version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
      - image: fauna/faunadb:latest
    steps:
      - checkout
      - run:
          name: update-npm
          command: npm install
      - run:
          name: test-faunadb
          command: 'curl http://localhost:8443/ping'
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
